# Generated by Django 4.2.1 on 2023-05-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Driver',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='Email',
            new_name='email',
        ),
    ]
