# Generated by Django 4.2.1 on 2023-05-16 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Driver', '0002_rename_customuser_driver_rename_email_driver_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.SmallIntegerField(choices=[(0, 'Bilik'), (1, 'Kenderaan')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('participant', models.IntegerField(default=1)),
                ('status', models.SmallIntegerField(choices=[(0, 'Menuggu'), (1, 'Diluluskan'), (2, 'Tidak Diluluskan')], default=0)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Driver.driver')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Room.myroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
