# Generated by Django 4.2.1 on 2023-05-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_rename_customuser_driver_rename_email_driver_email'),
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Driver.driver'),
        ),
    ]
