# Generated by Django 4.2.1 on 2023-05-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_rename_customuser_driver_rename_email_driver_email'),
        ('Room', '0002_alter_reservation_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Driver.driver'),
        ),
    ]
