# Generated by Django 4.2.1 on 2023-05-18 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_reservation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
