# Generated by Django 4.2.1 on 2023-05-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20230512_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
